### ISSUE TITLE
Error when debugging

### ISSUE THREAD

**Issue by triceam** [jinmingjian/sde#33]
I'm seeing a vague error when launching the debugger from VS Code:

![image](https://cloud.githubusercontent.com/assets/974294/24622644/bc947786-1873-11e7-8892-0d6ba85f1aee.png)

I don't see any additional detail whats going wrong.  Is there a way to see additional information, or fetch the actual error message?  The debug console is blank.  Or, is this something that is known or has been seen before?

Code assistance seems to be working.  ex: 

![image](https://cloud.githubusercontent.com/assets/974294/24622693/da3dedf8-1873-11e7-856f-c20449ca91cb.png)

This is with VS Code 1.10.2, and pulling the latest sourcekite from master, building with Swift 3.1 (Xcode 8.3 toolchain).

From the terminal I can invoke the sample main.swift program without issue, so I'm assuming it has to be something with the language server integration, but I don't see an obvious way to dig in and find more detail.

**Comment by triceam** [comment]
Also, I tried the project here: https://github.com/jinmingjian/sde-demos
SDE seems to compile correctly (i see 'building..." and "build succeeded" messages.  If I added errors intentionally, I see them in the problems window. Compiled output runs fine in a terminal, but debugger fails with the same error.

terminal output:

```
$ ./testsrv02
x+y+ca_z = 123006
```

**Comment by triceam** [comment]
Running from local extension src code, I was able to grab this error from VS Code: 

```
Activating extension `jinmingjian.sde` failed:  Cannot find module '/Users/andrewtrice/Documents/dev/sde/out/src/clientMain'
Here is the error stack:  Error: Cannot find module '/Users/andrewtrice/Documents/dev/sde/out/src/clientMain'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:15:19227)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Function.s [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:24952)
    at d (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:15:20381)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:15:25325
    at then (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:13423)
    at t._doActualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:15:25285)
    at t._actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:15:24973)
    at t.e._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:10:29225)
    at t.$activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:15:25946)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:20690)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8:30686)
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8:31363)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by triceam** [comment]
After digging further, it looks like VSCode either 1) can't launch the debug session, or 2) launches, but fails to connect to the debug session, but I'm still not sure how to debug further.   In VS Code dev tools, I can see this error happens when spawning the debug process.

**Comment by jinmingjian** [comment]
@triceam thanks for reporting. I may do a checking for latest version of vscode under macOS.

can you post your debug output according to this comments:

https://github.com/jinmingjian/sde/issues/28#issuecomment-286942125

**Comment by triceam** [comment]
I tested with tracing enabled.  Here is a video showing what I am seeing:
https://youtu.be/wmLPGnpOqcs

Here is output of `SPM` channel in output panel (first an unsuccessful compile, then successful based on changes i made to make sure it was working):

```
Compile Swift Module 'testsrv02' (1 sources)
/Users/andrewtrice/Downloads/sde-demos-master/Sources/main.swift:53:1: error: use of unresolved identifier 'asdfasdf'
asdfasdf 
^~~~~~~~
<unknown>:0: error: build had 1 command failures
swift-build: error: exit(1): /Applications/Xcode_8.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/andrewtrice/Downloads/sde-demos-master/.build/debug.yaml

Compile Swift Module 'testsrv02' (1 sources)
Linking ./.build/debug/testsrv02
```

Here is output of the `Swift` output channel, which looks to me like event logs:
```
-->onInitialize isTracingOn=[true],
	skProtocolProcess=[/Users/andrewtrice/Documents/dev/sourcekite/.build/debug/sourcekite],skProtocolProcessAsShellCmd=[false]
-->onDidChangeConfiguration
-->onDidChangeConfiguration tracing: 
	    swiftDiverBinPath=[/usr/bin/swift],
		shellPath=[/bin/sh]
***sourcekite initializing with skProtocolProcess at [/Users/andrewtrice/Documents/dev/sourcekite/.build/debug/sourcekite]
-->SourcekiteResponseHandler constructor done
***initializeModuleMeta***
***getShellExecPath: /bin/sh
---onDidChangeContent
-->onDidChangeConfiguration
-->onDidChangeConfiguration tracing: 
	    swiftDiverBinPath=[/usr/bin/swift],
		shellPath=[/bin/sh]
***swift package describe stdout*** {
  "modules": [
    {
      "c99name": "testsrv02",
      "is_test": false,
      "module_type": "SwiftModule",
      "name": "testsrv02",
      "path": "/Users/andrewtrice/Downloads/sde-demos-master/Sources",
      "sources": [
        "main.swift"
      ],
      "type": "executable"
    }
  ],
  "name": "testsrv02",
  "path": "/Users/andrewtrice/Downloads/sde-demos-master"
}

to write request: {
  key.request: source.request.cursorinfo,
  key.sourcefile: "/Users/andrewtrice/Downloads/sde-demos-master/Sources/main.swift",
  key.offset: 641,
  key.compilerargs: ["/Users/andrewtrice/Downloads/sde-demos-master/Sources/main.swift","-I","/Users/andrewtrice/Downloads/sde-demos-master/.build/debug","-I","/usr/lib/swift/pm/"],
  key.sourcetext: "let x = 2\nvar y = x*2\nstruct SA {\n    var sa_a_String = \"I'am a\\n \\n\\n String in\\\" )SA.\\n\"\n    var sa_b_Int = 123\n    var sa_c_boolean = true\n    var sa_nil: Int? = nil\n}\nclass CB {\n   var cb_x = \"(\\nin\\n CB\"\n   var cb_sa = SA()\n}\nclass CA {\n    var ca_a_tuple = (200, \"OK\")\n    let ca_b_list = [\"a\",\"b\",\"c\"]\n    let ca_c_map = [\"red\":0xff0000,\"green\":0x00ff00,\"blue\":0x0000ff]\n    var ca_d_sa = SA()\n    var ca_cb = CB()\n    var ca_z = 123000\n} \n\n\n\n\n\n\n\n\n\n\n\nfunc add(_ x: Int, _ y: Int, _ ca: CA) -> Int {\n return x+y+ca.ca_z\n}\n\nfunc donothing() {\n return;\n}\n\nlet ca = CA()\nprint(\"x+y+ca_z = \\(add(x, y, ca))\")\ndonothing()\n\n\n\n//asdf\n\n\n\n\n\n\n//asdfasdf \n\n\n\n\n\n\n" 
}


0
{
}


---onDidChangeContent
to write request: {
  key.request: source.request.cursorinfo,
  key.sourcefile: "/Users/andrewtrice/Downloads/sde-demos-master/Sources/main.swift",
  key.offset: 640,
  key.compilerargs: ["/Users/andrewtrice/Downloads/sde-demos-master/Sources/main.swift","-I","/Users/andrewtrice/Downloads/sde-demos-master/.build/debug","-I","/usr/lib/swift/pm/"],
  key.sourcetext: "let x = 2\nvar y = x*2\nstruct SA {\n    var sa_a_String = \"I'am a\\n \\n\\n String in\\\" )SA.\\n\"\n    var sa_b_Int = 123\n    var sa_c_boolean = true\n    var sa_nil: Int? = nil\n}\nclass CB {\n   var cb_x = \"(\\nin\\n CB\"\n   var cb_sa = SA()\n}\nclass CA {\n    var ca_a_tuple = (200, \"OK\")\n    let ca_b_list = [\"a\",\"b\",\"c\"]\n    let ca_c_map = [\"red\":0xff0000,\"green\":0x00ff00,\"blue\":0x0000ff]\n    var ca_d_sa = SA()\n    var ca_cb = CB()\n    var ca_z = 123000\n} \n\n\n\n\n\n\n\n\n\n\n\nfunc add(_ x: Int, _ y: Int, _ ca: CA) -> Int {\n return x+y+ca.ca_z\n}\n\nfunc donothing() {\n return;\n}\n\nlet ca = CA()\nprint(\"x+y+ca_z = \\(add(x, y, ca))\")\ndonothing()\n\n\n\n//asdf\n\n\n\n\n\n\nasdfasdf \n\n\n\n\n\n\n" 
}


1
{
}


to write request: {
  key.request: source.request.cursorinfo,
  key.sourcefile: "/Users/andrewtrice/Downloads/sde-demos-master/Sources/main.swift",
  key.offset: 641,
  key.compilerargs: ["/Users/andrewtrice/Downloads/sde-demos-master/Sources/main.swift","-I","/Users/andrewtrice/Downloads/sde-demos-master/.build/debug","-I","/usr/lib/swift/pm/"],
  key.sourcetext: "let x = 2\nvar y = x*2\nstruct SA {\n    var sa_a_String = \"I'am a\\n \\n\\n String in\\\" )SA.\\n\"\n    var sa_b_Int = 123\n    var sa_c_boolean = true\n    var sa_nil: Int? = nil\n}\nclass CB {\n   var cb_x = \"(\\nin\\n CB\"\n   var cb_sa = SA()\n}\nclass CA {\n    var ca_a_tuple = (200, \"OK\")\n    let ca_b_list = [\"a\",\"b\",\"c\"]\n    let ca_c_map = [\"red\":0xff0000,\"green\":0x00ff00,\"blue\":0x0000ff]\n    var ca_d_sa = SA()\n    var ca_cb = CB()\n    var ca_z = 123000\n} \n\n\n\n\n\n\n\n\n\n\n\nfunc add(_ x: Int, _ y: Int, _ ca: CA) -> Int {\n return x+y+ca.ca_z\n}\n\nfunc donothing() {\n return;\n}\n\nlet ca = CA()\nprint(\"x+y+ca_z = \\(add(x, y, ca))\")\ndonothing()\n\n\n\n//asdf\n\n\n\n\n\n\nasdfasdf \n\n\n\n\n\n\n" 
}


2
{
}


to write request: {
  key.request: source.request.cursorinfo,
  key.sourcefile: "/Users/andrewtrice/Downloads/sde-demos-master/Sources/main.swift",
  key.offset: 641,
  key.compilerargs: ["/Users/andrewtrice/Downloads/sde-demos-master/Sources/main.swift","-I","/Users/andrewtrice/Downloads/sde-demos-master/.build/debug","-I","/usr/lib/swift/pm/"],
  key.sourcetext: "let x = 2\nvar y = x*2\nstruct SA {\n    var sa_a_String = \"I'am a\\n \\n\\n String in\\\" )SA.\\n\"\n    var sa_b_Int = 123\n    var sa_c_boolean = true\n    var sa_nil: Int? = nil\n}\nclass CB {\n   var cb_x = \"(\\nin\\n CB\"\n   var cb_sa = SA()\n}\nclass CA {\n    var ca_a_tuple = (200, \"OK\")\n    let ca_b_list = [\"a\",\"b\",\"c\"]\n    let ca_c_map = [\"red\":0xff0000,\"green\":0x00ff00,\"blue\":0x0000ff]\n    var ca_d_sa = SA()\n    var ca_cb = CB()\n    var ca_z = 123000\n} \n\n\n\n\n\n\n\n\n\n\n\nfunc add(_ x: Int, _ y: Int, _ ca: CA) -> Int {\n return x+y+ca.ca_z\n}\n\nfunc donothing() {\n return;\n}\n\nlet ca = CA()\nprint(\"x+y+ca_z = \\(add(x, y, ca))\")\ndonothing()\n\n\n\n//asdf\n\n\n\n\n\n\nasdfasdf \n\n\n\n\n\n\n" 
}


3
{
}


---onDidChangeContent
```

The `Extensions` and `JSON Language Server` output channels are empty.

**Comment by jinmingjian** [comment]
@triceam thanks for preparing the materials forr reporting. 

The debugger (adapter) depends on the lldb on the path. You should make sure the lldb can be found in /usr/bin/lldb. check this by the follow commands:

> lldb --version

> which lldb

and as mentioned above, the language side features are independent with debugging side things. 


The life is hard. It is pity that there is still no server side Swift job in the world to make me pinned to the server side Swift. Then I will not focus on this extension in the following time. But I am still satisfied with the current of SDE by comparing the other competitor like vscode-rust, vscode-java.

I am planning to do some update to the readme for officially released 3.1.

**Comment by triceam** [comment]
Thanks @jinmingjian, I really appreciate the help.  Can you think of any other reasons why it might not be launching, or what else I should check?  It looks like `lldb` is on the path correctly.

```
$ lldb --version
lldb-370.0.37
  Swift-3.1

$  which lldb
/usr/bin/lldb
```

**Comment by jinmingjian** [comment]
@triceam sorry, I made a mistake. You should check against __lldb-mi__:

it seems my vm box of macOS also has not such executable in /usr/bin. So, I need to find where it is in the macOS... If you find it, you can do a sym link it to /usr/bin/lldb-mi, then everythiny should be OK... Or you can not understand this, please wait a moment for me.

**Comment by triceam** [comment]
Thanks!  I found it and did the following (I used `/usr/local/bin` instead of `/usr/bin` b/c I was getting "Operation not permitted" errors trying to simlink against `/user/bin`)

```
$ sudo mkdir -p /usr/local/bin
$ sudo ln -s /Applications/Xcode_8.3.app/Contents/Developer/usr/bin/lldb-mi /usr/local/bin/lldb-mi
$ which lldb-mi
/usr/local/bin/lldb-mi
```

This adds to the path correctly, and the error is not appearing anymore, but the debugger doesnt seem to launch.

Now it just seems to hang and show the animated indeterminate progress indicator while it waits to connect to a session.  I think we're headed in the right direction.  Can you think of anything else it might be looking for?

**CORRECTION:** it doesn't hang... that was an error on my part.  I try to launch, I see the progress indicator, then it looks like the process exits silently.  There's no output on the debug console.

**Comment by triceam** [comment]
Oh wait... I can hit breakpoints now.  It is working. Thank you!   It just looks like I don't see the output of `print()` statements.   Should I see that?

**Comment by jinmingjian** [comment]
@triceam  "no output on the debug console" is a bug in https://github.com/jinmingjian/sde/issues/22

**Comment by triceam** [comment]
ok, thanks.  looks like it's working!

**Comment by jinmingjian** [comment]
@triceam great to hear it works for you. The debugging functionalities are still in its early phase...
