### ISSUE TITLE
missing dependant sourcekite tool, please configure correct "swift.path.sourcekite"

### ISSUE THREAD

**Issue by JustinMoser** [jinmingjian/sde#43]
Hi,
I am unable to use this extension. I am running VS Code on macOS High Sierra, and i get the above error message. This is the output:

```
justinmoser/.vscode/extensions/vknabel.vscode-swift-development-environment-2.1.2/out/src/server/sourcekites.js:43
        throw err;
        ^

Error: spawn swift build -Xswiftc -framework -Xswiftc sourcekitd -Xswiftc -F -Xswiftc /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib -Xlinker -rpath -Xlinker /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Error - 18:10:48] Connection to server got closed. Server will not be restarted.
```

I have run the build / link command as instructed on the sourcekite repo page. From my root directory (HD root):

`> git clone https://github.com/jinmingjian/sourcekite.git`
`> cd sourcekite`
`> swift build -Xswiftc -framework -Xswiftc sourcekitd -Xswiftc -F -Xswiftc /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib -Xlinker -rpath -Xlinker /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib`

and then added this to my settings.json file, under the user settings tab:

`"swift.path.sourcekite": "/Users/justinmoser/sourcekite/.build/debug/sourcekite"`

I also get the message:

`Incorrect type. Expected "array".`

in the launch.json file on this key:

`"configurations": "sde.commands.debug.provideInitialConfigurations"`

**Comment by vknabel** [comment]
@JustinMoser you have installed my fork of this repository. I moved your issue to the new location.
